INSERT INTO Drugs (Name, ActiveSubstance, Form, DosageMg, Company, Category, Price)
VALUES
(N'Parol', N'Parasetamol', N'Tablet', 500, N'Atabay', N'Ağrı Kesici', 25.00),
(N'Vermidon', N'Parasetamol', N'Tablet', 500, N'Sanofi', N'Ağrı Kesici', 32.50),
(N'Majezik', N'Flurbiprofen', N'Tablet', 100, N'Sanovel', N'Ağrı Kesici', 48.00),
(N'Apranax', N'Naproksen', N'Tablet', 550, N'Abdi İbrahim', N'Ağrı Kesici', 55.00),
(N'Arveles', N'Deksketoprofen', N'Tablet', 25, N'Menarini', N'Ağrı Kesici', 52.00),
(N'Dolorex', N'Diklofenak', N'Tablet', 50, N'Abdi İbrahim', N'Ağrı Kesici', 40.00),
(N'Contramal', N'Tramadol', N'Kapsül', 50, N'Abdi İbrahim', N'Ağrı Kesici', 85.00),
(N'Doliprane', N'Parasetamol', N'Tablet', 500, N'Sanofi', N'Ağrı Kesici', 29.00),
(N'Minoset', N'Parasetamol', N'Şurup', 160, N'Bilim', N'Ağrı Kesici', 24.00),
(N'Calpol', N'Parasetamol', N'Şurup', 120, N'GSK', N'Ağrı Kesici', 23.00),
(N'İbufen', N'Ibuprofen', N'Şurup', 100, N'Abdi İbrahim', N'Ağrı Kesici', 30.00),
(N'Brufen', N'Ibuprofen', N'Tablet', 400, N'Abdi İbrahim', N'Ağrı Kesici', 42.00),
(N'Dolven', N'Ibuprofen', N'Şurup', 100, N'Sanofi', N'Ağrı Kesici', 28.00),
(N'Cataflam', N'Diklofenak Potasyum', N'Tablet', 50, N'Novartis', N'Ağrı Kesici', 44.00),
(N'Voltaren', N'Diklofenak', N'Jel', NULL, N'Novartis', N'Dermatoloji', 38.00),
(N'Aferin', N'Parasetamol + Fenilefrin', N'Tablet', NULL, N'Abdi İbrahim', N'Soğuk Algınlığı', 28.00),
(N'Tylol Hot', N'Parasetamol + Fenilefrin', N'Saşe', NULL, N'Nobel', N'Soğuk Algınlığı', 30.00),
(N'Gripin', N'Parasetamol + Kafein', N'Tablet', NULL, N'Bilim', N'Soğuk Algınlığı', 22.00),
(N'Augmentin', N'Amoksisilin + Klavulanik Asit', N'Tablet', 625, N'GSK', N'Antibiyotik', 78.50),
(N'Largopen', N'Amoksisilin', N'Tablet', 1000, N'Bilim', N'Antibiyotik', 65.00),
(N'Cefaks', N'Cefuroksim', N'Tablet', 500, N'Dea', N'Antibiyotik', 84.00),
(N'Zinnat', N'Cefuroksim', N'Süspansiyon', 250, N'GSK', N'Antibiyotik', 72.00),
(N'Rocacef', N'Seftriakson', N'Enjeksiyon', 1000, N'Deva', N'Antibiyotik', 96.00),
(N'Levoxin', N'Levofloksasin', N'Tablet', 500, N'Deva', N'Antibiyotik', 120.00),
(N'Zithromax', N'Azitromisin', N'Tablet', 500, N'Pfizer', N'Antibiyotik', 95.00),
(N'Klacid', N'Klaritromisin', N'Tablet', 500, N'Abbott', N'Antibiyotik', 98.00),
(N'Flagyl', N'Metronidazol', N'Tablet', 500, N'Sanofi', N'Antibiyotik', 40.00),
(N'Biteral', N'Ornidazol', N'Tablet', 500, N'Nobel', N'Antibiyotik', 42.00),
(N'Enfluvir', N'Oseltamivir', N'Kapsül', 75, N'Sanofi', N'Antiviral', 150.00),
(N'Tamiflu', N'Oseltamivir', N'Kapsül', 75, N'Roche', N'Antiviral', 175.00),
(N'Nexium', N'Esomeprazol', N'Kapsül', 40, N'AstraZeneca', N'Mide İlacı', 95.00),
(N'Lansor', N'Lansoprazol', N'Kapsül', 30, N'Sanovel', N'Mide İlacı', 62.00),
(N'Pantpas', N'Pantoprazol', N'Tablet', 40, N'Abdi İbrahim', N'Mide İlacı', 38.00),
(N'Losec', N'Omeprazol', N'Kapsül', 20, N'AstraZeneca', N'Mide İlacı', 52.00),
(N'Gaviscon', N'Aljinat + Karbonat', N'Süspansiyon', NULL, N'Reckitt', N'Mide İlacı', 47.00),
(N'Rennie', N'Kalsiyum + Magnezyum Karbonat', N'Çiğneme Tablet', NULL, N'Bayer', N'Mide İlacı', 33.00),
(N'Buscopan', N'Hiyosin-N-Butilbromür', N'Tablet', 10, N'Sanofi', N'Gastroenteroloji', 37.00),
(N'Duspatalin', N'Mebeverin', N'Tablet', 135, N'Abbott', N'Gastroenteroloji', 88.00),
(N'Imodium', N'Loperamid', N'Kapsül', 2, N'Janssen', N'Gastroenteroloji', 36.00),
(N'Enterogermina', N'Bacillus clausii', N'Süspansiyon', NULL, N'Sanofi', N'Probiyotik', 92.00),
(N'Sab Simplex', N'Simetikon', N'Damla', NULL, N'Pfizer', N'Gastroenteroloji', 48.00),
(N'Aerius', N'Desloratadin', N'Tablet', 5, N'Organon', N'Alerji İlacı', 52.00),
(N'Zyrtec', N'Setirizin', N'Tablet', 10, N'UCB Pharma', N'Alerji İlacı', 35.00),
(N'Xyzal', N'Levocetirizin', N'Tablet', 5, N'Sanofi', N'Alerji İlacı', 40.00),
(N'Rhinolast', N'Azelastin', N'Burun Spreyi', NULL, N'Meda', N'Alerji İlacı', 70.00),
(N'Ventolin', N'Salbutamol', N'İnhaler', NULL, N'GSK', N'Astım-KOAH', 70.00),
(N'Symbicort', N'Budesonid + Formoterol', N'İnhaler', NULL, N'AstraZeneca', N'Astım-KOAH', 130.00),
(N'Seretide', N'Salmeterol + Flutikazon', N'İnhaler', NULL, N'GSK', N'Astım-KOAH', 145.00),
(N'Lustral', N'Sertralin', N'Tablet', 50, N'Pfizer', N'Psikiyatri', 115.00),
(N'Cipralex', N'Essitalopram', N'Tablet', 10, N'Lundbeck', N'Psikiyatri', 120.00),
(N'Wellbutrin', N'Bupropion', N'Tablet', 150, N'GSK', N'Psikiyatri', 160.00),
(N'Seroxat', N'Paroksetin', N'Tablet', 20, N'GSK', N'Psikiyatri', 135.00),
(N'Efexor XR', N'Venlafaksin', N'Kapsül', 75, N'Pfizer', N'Psikiyatri', 170.00),
(N'Remeron', N'Mirtazapin', N'Tablet', 30, N'Organon', N'Psikiyatri', 140.00),
(N'Diazem', N'Diazepam', N'Tablet', 5, N'Deva', N'Psikiyatri', 60.00),
(N'Glifor', N'Metformin', N'Tablet', 850, N'Abdi İbrahim', N'Diyabet', 32.00),
(N'Glucophage', N'Metformin', N'Tablet', 1000, N'Merck', N'Diyabet', 38.00),
(N'Diamed', N'Gliklazid', N'Tablet', 60, N'Abdi İbrahim', N'Diyabet', 45.00),
(N'Glarine', N'İnsülin Glargin', N'Enjeksiyon', 100, N'Sanofi', N'Diyabet', 210.00),
(N'Coraspin', N'Asetilsalisilik Asit', N'Tablet', 100, N'Bayer', N'Kardiyoloji', 18.00),
(N'Beloc Zok', N'Metoprolol', N'Tablet', 50, N'AstraZeneca', N'Tansiyon', 54.00),
(N'Nebilet', N'Nebivolol', N'Tablet', 5, N'Berlin-Chemie', N'Tansiyon', 75.00),
(N'Norvasc', N'Amlodipin', N'Tablet', 5, N'Pfizer', N'Tansiyon', 58.00),
(N'Tritace', N'Ramipril', N'Tablet', 5, N'Sanofi', N'Tansiyon', 50.00),
(N'Crestor', N'Rosuvastatin', N'Tablet', 10, N'AstraZeneca', N'Kolesterol', 130.00),
(N'Lipitor', N'Atorvastatin', N'Tablet', 20, N'Pfizer', N'Kolesterol', 110.00),
(N'Aldactone', N'Spironolakton', N'Tablet', 25, N'Pfizer', N'Kardiyoloji', 60.00),
(N'Lasix', N'Furosemid', N'Ampul', 20, N'Sanofi', N'Kardiyoloji', 32.00),
(N'Supradyn', N'Vitamin Kompleksi', N'Tablet', NULL, N'Bayer', N'Takviye', 79.00),
(N'Centrum', N'Vitamin Kompleksi', N'Tablet', NULL, N'Pfizer', N'Takviye', 85.00),
(N'Zincovit', N'Çinko + Vitamin', N'Tablet', NULL, N'Menarini', N'Takviye', 64.00),
(N'Ferplex', N'Demir (Polimaltoz)', N'Şurup', NULL, N'Abdi İbrahim', N'Takviye', 55.00),
(N'Devit-3', N'D3 Vitamini', N'Damla', NULL, N'Deva', N'Takviye', 35.00),
(N'Osteocare', N'Kalsiyum + D3', N'Tablet', NULL, N'Vitabiotics', N'Takviye', 90.00),
(N'Calcium Sandoz', N'Kalsiyum', N'Efervesan Tablet', NULL, N'Sandoz', N'Takviye', 70.00),
(N'Muscoril', N'Tiyokolşikosid', N'Ampul', 4, N'Zentiva', N'Kas Gevşetici', 45.00),
(N'Myoset', N'Tiyokolşikosid', N'Tablet', 4, N'Bilim', N'Kas Gevşetici', 52.00),
(N'Belogent', N'Betametazon + Gentamisin', N'Krem', NULL, N'Intendis', N'Dermatoloji', 48.00),
(N'Madecassol', N'Asiaticoside', N'Pomad', NULL, N'Bayer', N'Dermatoloji', 60.00),
(N'Bepanthen', N'Dekspantenol', N'Merhem', NULL, N'Bayer', N'Dermatoloji', 45.00),
(N'Fucidin', N'Fusidik Asit', N'Krem', NULL, N'LEO Pharma', N'Dermatoloji', 78.00),
(N'Acnelyse', N'Tretinoin', N'Krem', NULL, N'Abdi İbrahim', N'Dermatoloji', 60.00),
(N'Zoretanin', N'Izotretinoin', N'Kapsül', 20, N'Roche', N'Dermatoloji', 190.00),
(N'Otrivine', N'KsiloMetazolin', N'Burun Spreyi', NULL, N'GSK', N'Kulak-Burun-Boğaz', 32.00),
(N'Iliadin', N'Oksimetazolin', N'Burun Spreyi', NULL, N'Merck', N'Kulak-Burun-Boğaz', 34.00),
(N'Sterimar', N'Deniz Suyu', N'Burun Spreyi', NULL, N'Gilbert', N'Kulak-Burun-Boğaz', 48.00),
(N'Refresh', N'Lubrikan Göz Damlası', N'Göz Damlası', NULL, N'Allergan', N'Göz', 40.00),
(N'Systane', N'Lubrikan Göz Damlası', N'Göz Damlası', NULL, N'Alcon', N'Göz', 55.00),
(N'Tobrased', N'Tobramisin', N'Göz Damlası', NULL, N'Bilim', N'Göz', 68.00),
(N'Acular', N'Ketorolak', N'Göz Damlası', NULL, N'Allergan', N'Göz', 72.00),
(N'Yasmin', N'Drospirenon + Etinilestradiol', N'Tablet', NULL, N'Bayer', N'Jinekoloji', 150.00),
(N'Diane 35', N'Siproteron + Etinilestradiol', N'Tablet', NULL, N'Bayer', N'Jinekoloji', 140.00),
(N'Microgynon', N'Levonorgestrel + Etinilestradiol', N'Tablet', NULL, N'Bayer', N'Jinekoloji', 120.00),
(N'Levotiron', N'Levotiroksin', N'Tablet', 50, N'Abdi İbrahim', N'Endokrinoloji', 46.00),
(N'Euthyrox', N'Levotiroksin', N'Tablet', 100, N'Merck', N'Endokrinoloji', 52.00),
(N'Parol Forte', N'Parasetamol', N'Tablet', 550, N'Nobel', N'Ağrı Kesici', 26.25),
(N'Parol Plus', N'Parasetamol', N'Tablet', 450, N'İlko', N'Ağrı Kesici', 27.00),
(N'Parol Extra', N'Parasetamol', N'Tablet', 550, N'Recordati', N'Ağrı Kesici', 27.75),
(N'Vermidon Plus', N'Parasetamol', N'Tablet', 550, N'İlko', N'Ağrı Kesici', 34.12),
(N'Vermidon Extra', N'Parasetamol', N'Tablet', 450, N'Recordati', N'Ağrı Kesici', 35.10),
(N'Vermidon SR', N'Parasetamol', N'Tablet', 550, N'Santa Farma', N'Ağrı Kesici', 36.08),
(N'Majezik Extra', N'Flurbiprofen', N'Tablet', 110, N'Recordati', N'Ağrı Kesici', 50.40),
(N'Majezik SR', N'Flurbiprofen', N'Tablet', 90, N'Santa Farma', N'Ağrı Kesici', 51.84),
(N'Majezik Retard', N'Flurbiprofen', N'Tablet', 110, N'İbrahim Etem', N'Ağrı Kesici', 53.28),
(N'Apranax SR', N'Naproksen', N'Tablet', 600, N'Santa Farma', N'Ağrı Kesici', 57.75),
(N'Apranax Retard', N'Naproksen', N'Tablet', 500, N'İbrahim Etem', N'Ağrı Kesici', 59.40),
(N'Apranax Duo', N'Naproksen', N'Tablet', 600, N'Drogsan', N'Ağrı Kesici', 61.05),
(N'Arveles Retard', N'Deksketoprofen', N'Tablet', 30, N'İbrahim Etem', N'Ağrı Kesici', 54.60),
(N'Arveles Duo', N'Deksketoprofen', N'Tablet', 20, N'Drogsan', N'Ağrı Kesici', 56.16),
(N'Arveles Max', N'Deksketoprofen', N'Tablet', 30, N'Gen Ilaç', N'Ağrı Kesici', 57.72),
(N'Dolorex Duo', N'Diklofenak', N'Tablet', 55, N'Drogsan', N'Ağrı Kesici', 42.00),
(N'Dolorex Max', N'Diklofenak', N'Tablet', 45, N'Gen Ilaç', N'Ağrı Kesici', 43.20),
(N'Dolorex Forte', N'Diklofenak', N'Tablet', 55, N'Nobel', N'Ağrı Kesici', 44.40),
(N'Contramal Max', N'Tramadol', N'Kapsül', 55, N'Gen Ilaç', N'Ağrı Kesici', 89.25),
(N'Contramal Forte', N'Tramadol', N'Kapsül', 45, N'Nobel', N'Ağrı Kesici', 91.80),
(N'Contramal Plus', N'Tramadol', N'Kapsül', 55, N'İlko', N'Ağrı Kesici', 94.35),
(N'Doliprane Forte', N'Parasetamol', N'Tablet', 550, N'Nobel', N'Ağrı Kesici', 30.45),
(N'Doliprane Plus', N'Parasetamol', N'Tablet', 450, N'İlko', N'Ağrı Kesici', 31.32),
(N'Doliprane Extra', N'Parasetamol', N'Tablet', 550, N'Recordati', N'Ağrı Kesici', 32.19),
(N'Minoset Plus', N'Parasetamol', N'Şurup', 170, N'İlko', N'Ağrı Kesici', 25.20),
(N'Minoset Extra', N'Parasetamol', N'Şurup', 150, N'Recordati', N'Ağrı Kesici', 25.92),
(N'Minoset SR', N'Parasetamol', N'Şurup', 170, N'Santa Farma', N'Ağrı Kesici', 26.64),
(N'Calpol Extra', N'Parasetamol', N'Şurup', 130, N'Recordati', N'Ağrı Kesici', 24.15),
(N'Calpol SR', N'Parasetamol', N'Şurup', 110, N'Santa Farma', N'Ağrı Kesici', 24.84),
(N'Calpol Retard', N'Parasetamol', N'Şurup', 130, N'İbrahim Etem', N'Ağrı Kesici', 25.53),
(N'İbufen SR', N'Ibuprofen', N'Şurup', 110, N'Santa Farma', N'Ağrı Kesici', 31.50),
(N'İbufen Retard', N'Ibuprofen', N'Şurup', 90, N'İbrahim Etem', N'Ağrı Kesici', 32.40),
(N'İbufen Duo', N'Ibuprofen', N'Şurup', 110, N'Drogsan', N'Ağrı Kesici', 33.30),
(N'Brufen Retard', N'Ibuprofen', N'Tablet', 410, N'İbrahim Etem', N'Ağrı Kesici', 44.10),
(N'Brufen Duo', N'Ibuprofen', N'Tablet', 390, N'Drogsan', N'Ağrı Kesici', 45.36),
(N'Brufen Max', N'Ibuprofen', N'Tablet', 410, N'Gen Ilaç', N'Ağrı Kesici', 46.62),
(N'Dolven Duo', N'Ibuprofen', N'Şurup', 110, N'Drogsan', N'Ağrı Kesici', 29.40),
(N'Dolven Max', N'Ibuprofen', N'Şurup', 90, N'Gen Ilaç', N'Ağrı Kesici', 30.24),
(N'Dolven Forte', N'Ibuprofen', N'Şurup', 110, N'Nobel', N'Ağrı Kesici', 31.08),
(N'Cataflam Max', N'Diklofenak Potasyum', N'Tablet', 55, N'Gen Ilaç', N'Ağrı Kesici', 46.20),
(N'Cataflam Forte', N'Diklofenak Potasyum', N'Tablet', 45, N'Nobel', N'Ağrı Kesici', 47.52),
(N'Cataflam Plus', N'Diklofenak Potasyum', N'Tablet', 55, N'İlko', N'Ağrı Kesici', 48.84),
(N'Voltaren Forte', N'Diklofenak', N'Jel', NULL, N'Nobel', N'Dermatoloji', 39.90),
(N'Voltaren Plus', N'Diklofenak', N'Jel', NULL, N'İlko', N'Dermatoloji', 41.04),
(N'Voltaren Extra', N'Diklofenak', N'Jel', NULL, N'Recordati', N'Dermatoloji', 42.18),
(N'Aferin Plus', N'Parasetamol + Fenilefrin', N'Tablet', NULL, N'İlko', N'Soğuk Algınlığı', 29.40),
(N'Aferin Extra', N'Parasetamol + Fenilefrin', N'Tablet', NULL, N'Recordati', N'Soğuk Algınlığı', 30.24),
(N'Aferin SR', N'Parasetamol + Fenilefrin', N'Tablet', NULL, N'Santa Farma', N'Soğuk Algınlığı', 31.08),
(N'Tylol Hot Extra', N'Parasetamol + Fenilefrin', N'Saşe', NULL, N'Recordati', N'Soğuk Algınlığı', 31.50),
(N'Tylol Hot SR', N'Parasetamol + Fenilefrin', N'Saşe', NULL, N'Santa Farma', N'Soğuk Algınlığı', 32.40),
(N'Tylol Hot Retard', N'Parasetamol + Fenilefrin', N'Saşe', NULL, N'İbrahim Etem', N'Soğuk Algınlığı', 33.30),
(N'Gripin SR', N'Parasetamol + Kafein', N'Tablet', NULL, N'Santa Farma', N'Soğuk Algınlığı', 23.10),
(N'Gripin Retard', N'Parasetamol + Kafein', N'Tablet', NULL, N'İbrahim Etem', N'Soğuk Algınlığı', 23.76),
(N'Gripin Duo', N'Parasetamol + Kafein', N'Tablet', NULL, N'Drogsan', N'Soğuk Algınlığı', 24.42),
(N'Augmentin Retard', N'Amoksisilin + Klavulanik Asit', N'Tablet', 675, N'İbrahim Etem', N'Antibiyotik', 82.42),
(N'Augmentin Duo', N'Amoksisilin + Klavulanik Asit', N'Tablet', 575, N'Drogsan', N'Antibiyotik', 84.78),
(N'Augmentin Max', N'Amoksisilin + Klavulanik Asit', N'Tablet', 675, N'Gen Ilaç', N'Antibiyotik', 87.14),
(N'Largopen Duo', N'Amoksisilin', N'Tablet', 1050, N'Drogsan', N'Antibiyotik', 68.25),
(N'Largopen Max', N'Amoksisilin', N'Tablet', 950, N'Gen Ilaç', N'Antibiyotik', 70.20),
(N'Largopen Forte', N'Amoksisilin', N'Tablet', 1050, N'Nobel', N'Antibiyotik', 72.15),
(N'Cefaks Max', N'Cefuroksim', N'Tablet', 550, N'Gen Ilaç', N'Antibiyotik', 88.20),
(N'Cefaks Forte', N'Cefuroksim', N'Tablet', 450, N'Nobel', N'Antibiyotik', 90.72),
(N'Cefaks Plus', N'Cefuroksim', N'Tablet', 550, N'İlko', N'Antibiyotik', 93.24),
(N'Zinnat Forte', N'Cefuroksim', N'Süspansiyon', 260, N'Nobel', N'Antibiyotik', 75.60),
(N'Zinnat Plus', N'Cefuroksim', N'Süspansiyon', 240, N'İlko', N'Antibiyotik', 77.76),
(N'Zinnat Extra', N'Cefuroksim', N'Süspansiyon', 260, N'Recordati', N'Antibiyotik', 79.92),
(N'Rocacef Plus', N'Seftriakson', N'Enjeksiyon', 1050, N'İlko', N'Antibiyotik', 100.80),
(N'Rocacef Extra', N'Seftriakson', N'Enjeksiyon', 950, N'Recordati', N'Antibiyotik', 103.68),
(N'Rocacef SR', N'Seftriakson', N'Enjeksiyon', 1050, N'Santa Farma', N'Antibiyotik', 106.56),
(N'Levoxin Extra', N'Levofloksasin', N'Tablet', 550, N'Recordati', N'Antibiyotik', 126.00),
(N'Levoxin SR', N'Levofloksasin', N'Tablet', 450, N'Santa Farma', N'Antibiyotik', 129.60),
(N'Levoxin Retard', N'Levofloksasin', N'Tablet', 550, N'İbrahim Etem', N'Antibiyotik', 133.20),
(N'Zithromax SR', N'Azitromisin', N'Tablet', 550, N'Santa Farma', N'Antibiyotik', 99.75),
(N'Zithromax Retard', N'Azitromisin', N'Tablet', 450, N'İbrahim Etem', N'Antibiyotik', 102.60),
(N'Zithromax Duo', N'Azitromisin', N'Tablet', 550, N'Drogsan', N'Antibiyotik', 105.45),
(N'Klacid Retard', N'Klaritromisin', N'Tablet', 550, N'İbrahim Etem', N'Antibiyotik', 102.90),
(N'Klacid Duo', N'Klaritromisin', N'Tablet', 450, N'Drogsan', N'Antibiyotik', 105.84),
(N'Klacid Max', N'Klaritromisin', N'Tablet', 550, N'Gen Ilaç', N'Antibiyotik', 108.78),
(N'Flagyl Duo', N'Metronidazol', N'Tablet', 550, N'Drogsan', N'Antibiyotik', 42.00),
(N'Flagyl Max', N'Metronidazol', N'Tablet', 450, N'Gen Ilaç', N'Antibiyotik', 43.20),
(N'Flagyl Forte', N'Metronidazol', N'Tablet', 550, N'Nobel', N'Antibiyotik', 44.40),
(N'Biteral Max', N'Ornidazol', N'Tablet', 550, N'Gen Ilaç', N'Antibiyotik', 44.10),
(N'Biteral Forte', N'Ornidazol', N'Tablet', 450, N'Nobel', N'Antibiyotik', 45.36),
(N'Biteral Plus', N'Ornidazol', N'Tablet', 550, N'İlko', N'Antibiyotik', 46.62),
(N'Enfluvir Forte', N'Oseltamivir', N'Kapsül', 80, N'Nobel', N'Antiviral', 157.50),
(N'Enfluvir Plus', N'Oseltamivir', N'Kapsül', 70, N'İlko', N'Antiviral', 162.00),
(N'Enfluvir Extra', N'Oseltamivir', N'Kapsül', 80, N'Recordati', N'Antiviral', 166.50),
(N'Tamiflu Plus', N'Oseltamivir', N'Kapsül', 80, N'İlko', N'Antiviral', 183.75),
(N'Tamiflu Extra', N'Oseltamivir', N'Kapsül', 70, N'Recordati', N'Antiviral', 189.00),
(N'Tamiflu SR', N'Oseltamivir', N'Kapsül', 80, N'Santa Farma', N'Antiviral', 194.25),
(N'Nexium Extra', N'Esomeprazol', N'Kapsül', 45, N'Recordati', N'Mide İlacı', 99.75),
(N'Nexium SR', N'Esomeprazol', N'Kapsül', 35, N'Santa Farma', N'Mide İlacı', 102.60),
(N'Nexium Retard', N'Esomeprazol', N'Kapsül', 45, N'İbrahim Etem', N'Mide İlacı', 105.45),
(N'Lansor SR', N'Lansoprazol', N'Kapsül', 35, N'Santa Farma', N'Mide İlacı', 65.10),
(N'Lansor Retard', N'Lansoprazol', N'Kapsül', 25, N'İbrahim Etem', N'Mide İlacı', 66.96),
(N'Lansor Duo', N'Lansoprazol', N'Kapsül', 35, N'Drogsan', N'Mide İlacı', 68.82),
(N'Pantpas Retard', N'Pantoprazol', N'Tablet', 45, N'İbrahim Etem', N'Mide İlacı', 39.90),
(N'Pantpas Duo', N'Pantoprazol', N'Tablet', 35, N'Drogsan', N'Mide İlacı', 41.04),
(N'Pantpas Max', N'Pantoprazol', N'Tablet', 45, N'Gen Ilaç', N'Mide İlacı', 42.18),
(N'Losec Duo', N'Omeprazol', N'Kapsül', 25, N'Drogsan', N'Mide İlacı', 54.60),
(N'Losec Max', N'Omeprazol', N'Kapsül', 15, N'Gen Ilaç', N'Mide İlacı', 56.16),
(N'Losec Forte', N'Omeprazol', N'Kapsül', 25, N'Nobel', N'Mide İlacı', 57.72),
(N'Gaviscon Max', N'Aljinat + Karbonat', N'Süspansiyon', NULL, N'Gen Ilaç', N'Mide İlacı', 49.35),
(N'Gaviscon Forte', N'Aljinat + Karbonat', N'Süspansiyon', NULL, N'Nobel', N'Mide İlacı', 50.76),
(N'Gaviscon Plus', N'Aljinat + Karbonat', N'Süspansiyon', NULL, N'İlko', N'Mide İlacı', 52.17);